# -*- coding: utf-8 -*-
# Copyright (C) 2024 Benjamin Thomas Schwertfeger
# GitHub: https://github.com/btschwertfeger
#

name: CI/CD

on:
  push:
    branches: [master]
  schedule:
    - cron: "20 16 */7 * *"
  release:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  Pre-Commit:
    uses: ./.github/workflows/_pre_commit.yaml

  Build:
    uses: ./.github/workflows/_build.yaml
